audit_header: false
title: -- MARKET -- Real Estate Video Blog with Lela Ashkarian & Natalie Ardis
description: Our mission at Luxury Island Properties is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Luxury Island Properties, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Lela Ashkarian & Natalie Ardis
  title:
  license_number:
  about_markdown: |
    As a Real Estate Top Agent/Consultant for Coldwell Banker Schmitt Real Estate, a prime real estate company of the Florida Keys area, and with over 22 years of experience in the industry, Lela is highly regarded by co-workers and clients for her professionalism and keen industry knowledge. On a daily basis, she has primarily engaged in advertising ocean and beachfront properties, generating leads, screening potential buyers, setting up appointments, and researching competitive market prices. That's what this business is all about for Lela.

    Natalie attended high school at Marathon High School in the heart of the Florida Keys.  After high school she attended the University of Central Florida with her Associates Degree and received her Bachelors Degree in Marketing from Nova Southeastern University.  Joining Coldwell Banker Schmitt Real Estate Co. in 2010, she was given a wonderful opportunity to help others find their piece of paradise. Natalie has enthusiasm, drive, passion and communication that truly is able to set her apart in the real estate business; "It is my job to make sure my customers get the best service and guidance possible." Natalie's goal for sellers is to use Coldwell Banker Schmitt's "Everyday Until It Is Sold" Marketing program to get sellers the best terms and price for their home. Natalie enjoys fishing, diving, volleyball, traveling, a good glass of wine enjoying the keys sunsets. Natalie enjoys giving back to the community through various organizations some include a board of director at Grace Jones Community Center and Secretary for Coldwell Banker Schmitt Charitable Foundation. "The Keys has such a great sense of community that when someone needs a helping hand the whole community steps forward, that is one of the best things about this place of course in addition to fishing and diving!"
  brand: Luxury Island Properties
  brokerage: Coldwell Banker - Schmitt Real Estate Co.
  market:
  address:
  phone: 305-395-0814
  phone_type: Lela
  phone2: 305-481-3317
  phone2_type: Natalie
  email: Lela@CBSchmitt.com
  email2: NatalieArdis5@Gmail.com
  url:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with Lela Ashkarian & Natalie Ardis'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Luxury Island Properties - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Lela Ashkarian & Natalie Ardis'

images:
  client_headshot_path: /img/headshot.jpg
  client_headshot_path2: /img/headshot2.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#03528b'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#0f1f36'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
